FROM --platform=$BUILDPLATFORM alpine:latest
ARG TARGETARCH


RUN apk update && apk add --no-cache bash && \
    apk --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community add yq


# RUN adduser -D -s /bin/sh sutility
# USER sutility
# WORKDIR /home/sutility


CMD ["/bin/bash"]
