FROM --platform=$TARGETPLATFORM alpine:latest
ARG TARGETARCH


RUN apk update \
 && apk add --no-cache bash \
 && apk add --no-cache openssh


RUN adduser -D -s /bin/sh sutility
USER sutility
WORKDIR /home/sutility


CMD ["/bin/bash"]
