FROM --platform=$TARGETPLATFORM alpine:latest
ARG TARGETARCH

# git-lfs is still not released on the alpine package index and it still has some critical vulnerabilities
# see https://github.com/git-lfs/git-lfs/issues/6051
RUN apk update \
 && apk add --no-cache bash \
 && apk --no-cache add git git-lfs gpg less openssh patch perl && git lfs install


RUN adduser -D -s /bin/sh sutility
USER sutility
WORKDIR /home/sutility


CMD ["/bin/bash"]
