name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  schedule:
    - cron: '0 0 * * 5'  # every Friday at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: log in to docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: sutility
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: extract docker metadata for main image
        id: meta-main
        uses: docker/metadata-action@v5
        with:
          images: sutility/sutility
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: extract docker metadata for sutility-kubectl
        id: meta-kubectl
        uses: docker/metadata-action@v5
        with:
          images: sutility/sutility-kubectl
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: extract docker metadata for sutility-openssh
        id: meta-openssh
        uses: docker/metadata-action@v5
        with:
          images: sutility/sutility-openssh
          tags: |
            type=raw,value=latest
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: build and push main docker image
        id: build-and-push-main
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-main.outputs.tags }}
          labels: ${{ steps.meta-main.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push sutility-kubectl
        id: build-and-push-kubectl
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.kubectl
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-kubectl.outputs.tags }}
          labels: ${{ steps.meta-kubectl.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: build and push sutility-openssh
        id: build-and-push-openssh
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.openssh
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-openssh.outputs.tags }}
          labels: ${{ steps.meta-openssh.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
